### ISSUE TITLE
[feat] qs settings overrides and UMD export value

### ISSUE THREAD

**Issue by GabeMedrash** [coffeedoughnuts/pram#1]
Hi there,

This library looks to be a very helpful abstraction--been evaluating its use to save me from re-implementing almost exactly the same functionality. I'm wondering if you would accept two small PRs:
1. Accept optional `parseOptions` and `stringifyOptions` through the constructor, to pass on to the `qs.parse`, `qs.stringify` calls.
2. Modify the Webpack configuration to make the UMD exposed value simply `Pram`. Currently, when included via a script tag, I have to write `new [window].pram.default()`. Once updated, the usage would change to `new [window].Pram()`.

Let me know and I'd be happy to submit--thanks!

**Comment by GabeMedrash** [comment]
Thanks! Will send out some PRs early next week. Using the function approach sounds interesting. I suppose it's more of a hassle ergonomics-wise, especially considering the marshalling library of choice would become an explicit dependency, versus a transitive one. But I like the approach overall. Thinking of the times I wished an abstraction library just updated a dependency to take advantage of some new feature I needed--this side-steps that completely. Plus, it's consistent with how `history` is managed. So, seems like win.

I would think `parser` and `stringifier` would be optional to send in, but I'd wonder, if they were optional, and `pram` pulled in version "x" of `qs` and I send in version "y" for `stringifier`, would we run into dependency version issues? I'm not quite familiar enough with how NPM (or yarn) resolves deps to know. Something to investigate I suppose.

**Comment by coffeedoughnuts** [comment]
I *think* npm >= 3 should handle that kind of dependency conflict - let's give it a go and see!

**Comment by coffeedoughnuts** [comment]
your PR was merged for the Webpack config change, and released as `2.0.0-alpha.0` (alpha because soon I hope to add more features and another breaking change to the API)

**Comment by GabeMedrash** [comment]
Sweet, thanks! Will ~likely~ have the other PR out by tonight

**Comment by GabeMedrash** [comment]
So. Didn't end up making that other PR, primarily because I found that I didn't really need the additional functionality--then promptly forgot about it (work/life/etc). Apologies for the silence. Going to close this out so that the issue doesn't unnecessarily linger.
